sudo: required
dist: trusty

addons:
  chrome: stable

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications.email: false

branches.except: "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn e2e
