sudo: required
dist: trusty

addons.apt:
  update: true
  sources: google-chrome
  packages: google-chrome-stable

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications.email: false

node_js: '10'

branches.except: "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update  
script:
  - yarn build
  - yarn test
  - yarn e2e
after_script:
  - greenkeeper-lockfile-upload
